### ISSUE TITLE
Setup of capstone project

### ISSUE THREAD

**Issue by indigodavid** [indigodavid/metropolitan-museum-of-art#25]
➡️ Project link: https://github.com/indigodavid/metropolitan-museum-of-art/projects/2

➡️ For the capstone project we are two members:

- ✔️ Brenda Wihogora
- ✔️ David Vera

Happy reviewing! 😀

**Comment by thecodechaser** [comment]
## STATUS: APPROVED 🟢

## Hi @indigodavid, and @Brenda309👋, 

Your project is complete!  There is nothing else to say other than... it's time to close it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
