### ISSUE TITLE
Searched Items taking too long

### ISSUE THREAD

**Issue by GiuseppeTG** [indigodavid/metropolitan-museum-of-art#32]
### Highlights

✔️ Clean code
✔️ Nice design

### Works slow

https://github.com/indigodavid/metropolitan-museum-of-art/blob/059581d2271bf809f590afab1ff53d8cbebde8e3/src/modules/get-searched.js#L1-L10
You may want to limit the number of objects that the search function returns. You can limit it with `slice()`.

I think it is a very good project! Congratulations 👍

**Comment by indigodavid** [comment]
Hi @GiuseppeTG thank you for your recommendation. The latest implementation implements a variation of the changes proposed and the website is working faster. Thanks for your advice. Best regards and happy coding!!
